;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-babel-insert-hyphen
        backward-sexp
        dabbrev-expand
        delete-horizontal-space
        delete-indentation
        electric-newline-and-maybe-indent
        forward-sexp
        kill-sexp
        mwim-beginning-of-code-or-line
        mwim-end-of-line-or-code
        my:insert-tab-or-spaces
        my:python-magic-single-quote
        org-beginning-of-line
        org-self-insert-command
        paredit-backslash
        paredit-backward-kill-word
        paredit-forward
        paredit-forward-delete
        paredit-forward-down
        paredit-forward-kill-word
        paredit-raise-sexp
        paredit-semicolon
        paredit-splice-sexp
        paredit-split-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        describe-key-briefly
        ivy-swp-switch-to-buffer-overload
        minions-minor-modes-menu
        sql-send-paragraph
        ))
