;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-babel-insert-hyphen
        backward-sexp
        dabbrev-expand
        delete-horizontal-space
        delete-indentation
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        faux-indent-delete-backward-indent-or-char
        forward-sexp
        indent-for-tab-command
        kill-sexp
        markdown-insert-code
        markdown-outdent-or-delete
        mwim-beginning-of-code-or-line
        mwim-end-of-line-or-code
        my:insert-tab-or-spaces
        my:python-magic-double-quote
        my:python-magic-single-quote
        org-beginning-of-line
        org-delete-char
        org-self-insert-command
        paredit-backslash
        paredit-backward-kill-word
        paredit-forward
        paredit-forward-delete
        paredit-forward-down
        paredit-forward-kill-word
        paredit-open-round
        paredit-raise-sexp
        paredit-semicolon
        paredit-splice-sexp
        paredit-split-sexp
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        avy-goto-char
        beginning-of-buffer
        counsel-describe-function
        counsel-projectile-find-file
        describe-key-briefly
        edit-indirect-region
        ivy-switch-buffer-other-window
        ivy-swp-switch-to-buffer-overload
        minions-minor-modes-menu
        sql-send-paragraph
        ))
