(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(bmkp-last-as-first-bookmark-file "~/.emacs.d/bookmarks")
 '(package-selected-packages
   '(
     ace-window
     adaptive-wrap
     aggressive-indent
     all-the-icons
     amx
     auctex
     auto-compile
     auto-highlight-symbol
     auto-package-update
     avy
     bind-key
     bookmark+
     clean-aindent-mode
     command-log-mode
     comment-dwim-2
     company
     company-anaconda
     company-auctex
     company-reftex
     company-shell
     company-statistics
     company-web
     counsel
     counsel-css
     counsel-projectile
     csv-mode
     dash
     deft
     diff-hl
     dired-narrow
     dockerfile-mode
     dtrt-indent
     dumb-jump
     edit-indirect
     edit-server
     el-patch
     eltu
     emmet-mode
     exec-path-from-shell
     expand-region
     flx
     flycheck
     flycheck-haskell
     flycheck-package
     flycheck-pos-tip
     free-keys
     god-mode
     graphviz-dot-mode
     haskell-mode
     haskell-snippets
     highlight-indent-guides
     highlight-parentheses
     hindent
     hl-line+
     hl-todo
     hlint-refactor
     hydra
     imenu-list
     impatient-mode
     importmagic
     intero
     ivy
     ivy-hydra
     ivy-xref
     ivy-yasnippet
     js2-mode
     js2-refactor
     json-mode
     key-chord
     link-hint
     loccur
     lorem-ipsum
     lua-mode
     macrostep
     magit
     markdown-mode
     minions
     move-text
     multi-line
     multiple-cursors
     mwim
     ns-copy-html
     org-plus-contrib
     orgtbl-aggregate
     osx-dictionary
     package-build
     paradox
     paredit
     persp-mode
     phi-search
     projectile
     python
     pyvenv
     quelpa
     rainbow-mode
     scss-mode
     sly
     smart-tabs
     smartparens
     sql-indent
     sqlup-mode
     sticky-region
     swiper
     transpose-frame
     treepy
     undo-tree
     unfill
     unicode-fonts
     volatile-highlights
     web-beautify
     web-mode
     webpaste
     wgrep
     which-key
     window-purpose
     winum
     yaml-mode
     yasnippet
     yasnippet-snippets
     zop-to-char
     ))
 '(paradox-github-token t)
 '(safe-local-variable-values
   '((eltu-exuberant-ctags-additional-arguments "--python-kinds=-i" "--languages=-html,-php,-javascript"))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
