(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ahs-idle-interval 0.5)
 '(bmkp-last-as-first-bookmark-file "~/.emacs.d/bookmarks")
 '(org-modules
   '(org-tempo org-id ol-w3m ol-bbdb ol-bibtex ol-docview ol-gnus ol-info ol-irc ol-mhe ol-rmail ol-eww))
 '(package-selected-packages
   '(
     ace-window
     adaptive-wrap
     aggressive-indent
     all-the-icons
     amx
     anzu
     atomic-chrome
     auctex
     auto-compile
     auto-highlight-symbol
     auto-package-update
     auto-yasnippet
     avy
     bind-key
     blackout
     bookmark+
     buttercup
     cider
     clean-aindent-mode
     command-log-mode
     comment-dwim-2
     company
     company-auctex
     company-prescient
     company-reftex
     company-shell
     company-terraform
     company-web
     counsel
     counsel-css
     counsel-projectile
     crontab-mode
     crux
     csv-mode
     dash
     deft
     diff-hl
     dired-narrow
     dired-ranger
     dockerfile-mode
     dtrt-indent
     dumb-jump
     edit-indirect
     editorconfig
     el-patch
     elpy
     eltu
     embrace
     emmet-mode
     exec-path-from-shell
     expand-region
     fennel-mode
     flx
     flycheck
     flycheck-clj-kondo
     flycheck-haskell
     flycheck-package
     flycheck-pos-tip
     free-keys
     graphviz-dot-mode
     groovy-mode
     haskell-mode
     haskell-snippets
     highlight-indent-guides
     highlight-parentheses
     hindent
     hl-line+
     hl-todo
     hlint-refactor
     hydra
     imenu-list
     impatient-mode
     intero
     ivy
     ivy-avy
     ivy-bibtex
     ivy-hydra
     ivy-prescient
     ivy-xref
     ivy-yasnippet
     js2-mode
     js2-refactor
     json-mode
     key-chord
     link-hint
     literate-calc-mode
     loccur
     lorem-ipsum
     lua-mode
     macrostep
     magit
     markdown-mode
     minions
     modus-vivendi-theme
     monroe
     move-text
     multi-line
     multiple-cursors
     mwim
     nhexl-mode
     ns-copy-html
     olivetti
     org-plus-contrib
     orgtbl-aggregate
     osx-dictionary
     package-build
     pandoc-mode
     paradox
     paredit
     persp-mode
     phi-search
     projectile
     python
     pyvenv
     quelpa
     rainbow-mode
     reformatter
     scss-mode
     shackle
     shift-number
     sly
     smart-tabs
     smartparens
     sql-indent
     sqlup-mode
     sticky-region
     swiper
     systemd
     terraform-doc
     terraform-mode
     transpose-frame
     treemacs
     treepy
     undo-tree
     unfill
     unicode-fonts
     vcl-mode
     volatile-highlights
     web-beautify
     web-mode
     webpaste
     wgrep
     which-key
     winum
     yaml-mode
     yasnippet
     yasnippet-snippets
     zop-to-char
     ))
 '(paradox-github-token t)
 '(safe-local-variable-values
   '((elpy-rpc-virtualenv-path . current)
     (eltu-exuberant-ctags-additional-arguments "--python-kinds=-i" "--languages=-html,-php,-javascript"))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
